### ISSUE TITLE
Adding new redirect forced to enter value into search textbox

### ISSUE THREAD

**Issue by shgreignavico** [Geta/404handler#106]
![image](https://user-images.githubusercontent.com/35337204/40064472-80332952-5857-11e8-8772-ee28314d91e8.png)

When adding a new redirect I am forced to enter in a search term before submitting. 
This appears to be because the textbox is marked as required                     
<input type="text" class="notfound-search" name="searchWord" required/>

**Comment by marisks** [comment]
This is fixed in 11.1.12 and 10.3.11
