### ISSUE TITLE
An error has occured in the dynamic data store

### ISSUE THREAD

**Issue by bogdanstojanovic** [Geta/404handler#107]
We are using DXC and recently updated quite big batch of redirects (in total >4000 records). 
Error below comes every day and application restart resolve the problem for some time - minutes. 
Any thoughts how to resolve this?

_An error has occured in the dynamic data store: System.Threading.ThreadAbortException: Thread was being aborted. at System.AppDomain.GetId() at System.Threading.Thread.GetCurrentCultureNoAppX() at System.String.ToLower() at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirect.GetHashCode() at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at EPiServer.Data.Dynamic.DynamicDataStore.SetContextObjects(IDictionary`2 objects) at EPiServer.Data.Dynamic.DynamicDataStore.InternalLoad(Identity id, Type type, LoadAsObjectType loadAs, ProviderCallContext parentContext) at EPiServer.Data.Dynamic.Internal.EPiServerDynamicDataStore.Load[TResult](Identity id) at EPiServer.Data.Dynamic.Internal.DynamicDataCollection`1.DynamicDataCollectionEnumerator.get_Current() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.LoadCustomRedirects() at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.get_Current()_

**Comment by bogdanstojanovic** [comment]
An new error appeared: 

_> An error has occured in the dynamic data store: System.Threading.ThreadAbortException: Thread was being aborted. at System.Web.UnsafeNativeMethods.PerfIncrementCounter(IntPtr pCounters, Int32 number) at System.Web.PerfCounters.IncrementCounter(AppPerfCounter counter) at System.Web.Caching.CacheSingle.UpdateCache(CacheKey cacheKey, CacheEntry newEntry, Boolean replace, CacheItemRemovedReason removedReason, Object& valueOld) at System.Web.Caching.CacheInternal.DoGet(Boolean isPublic, String key, CacheGetOptions getOptions) at EPiServer.Data.Cache.HttpRuntimeCacheProvider.GetCore(String key) at EPiServer.Data.Cache.CacheProvider.GetInternal(String key, Type type, LoadingContext context) at EPiServer.Data.Dynamic.DynamicDataStore.InternalLoad(Identity id, Type type, LoadAsObjectType loadAs, ProviderCallContext parentContext) at EPiServer.Data.Dynamic.Internal.EPiServerDynamicDataStore.Load[TResult](Identity id) at EPiServer.Data.Dynamic.Internal.DynamicDataCollection`1.DynamicDataCollectionEnumerator.get_Current() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.LoadCustomRedirects() at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.get_Current()_

**Comment by marisks** [comment]
I found this: https://stackoverflow.com/questions/13413549/thread-was-being-aborted-while-looping-a-lot-of-rows

Maybe it would help.

**Comment by bogdanstojanovic** [comment]
Seems like recent  update helped us resolve the problem.
