### ISSUE TITLE
Custom Redirect Manager No Results - BVN Table 300,000+ records

### ISSUE THREAD

**Issue by toddfa** [Geta/404handler#109]
Greetings,

My organization recently setup an EpiServer platform and has been experiencing performance issues throughout the site. Knowing this while getting a feel for the epicms database I came across the table object BVN.NotFoundRequests. The table has over 300,000 records which after a few search results seemed to be an alarming number. As an example, this [thread](https://support.episerver.com/hc/en-us/articles/115004099183-Site-performance-impacted-by-BVN-404-handler) indicated 50,000 records was causing site performance issues.

Being new to EpiServer and 404Handler I went to the Epi platform to analyze how the Custom Redirect Manager widget worked. My understanding is all 404 errors are logged in the BVN.NotFoundRequests table which can then be managed by the widget in the platform.

**Concern**
My concern, and the reason for this post, is the Custom Redirect Manager returns no records even though the table has 300,000+ records.

**Questions**
1. Is 300,000 records in the table BVN.NotFoundRequests okay? Should routine maintenance be done?

2. Any reason why the widget is not pulling from the database? Ideas to fix?

Thank You in advance. 

note: EpiServer support referred me to this page.

**Comment by marisks** [comment]
BVN.NotFoundRequests logs 404 requests which are displayed in the Suggestions tab. As you have 300,000 records it is unlikely that you will use this feature. So you can disable logging of 404 requests and then delete the contents of BVN.NotFoundRequests table.

Regarding you Concern - the contents of this table are displayed under the Suggestions tab. Do you see there anything?

**Comment by marisks** [comment]
Closed as no response.
