### ISSUE TITLE
Is it possible to redirect with query string?

### ISSUE THREAD

**Issue by MichalGrzegorzak** [Geta/404handler#11]
Want to accomplish something like this (but I don`t know what query string there it will be):
/oldlink?x=123
to
/newlink?x=123

**Comment by Alacon** [comment]
Any news on this?

**Comment by mbrage83** [comment]
It would be really great if this can be fixed, or at least confirmed as an issue.

**Comment by permagne** [comment]
A simple solution to this is to add an INotFoundHandler, as described in in the Custom Handlers section: https://github.com/BVNetwork/404handler#custom-handlers

**Comment by frederikvig** [comment]
Another scenario is with hashes in the URL like: /my/page/#somehash. This is not working today and should be looked at together with the QueryStrings.

**Comment by LukaDevic** [comment]
This functionality has been added, don't check Wildcard box if you want query string to be appended to new URL. 
Closing this issue.
