### ISSUE TITLE
Redirect between domains

### ISSUE THREAD

**Issue by samboman** [Geta/404handler#111]
I have a site example.com.
example.com/sub are a sub-site of the main-site.

I have a secondary domain: sub-example.com. I want to redirect: 'http://sub-example.com' to 'https://example.com/sub'. I cant get it to work, or is it not a valid scenario?

![image](https://user-images.githubusercontent.com/1038277/40619278-b7325fda-6294-11e8-873a-7c9aa810dc16.png)

**Comment by marisks** [comment]
Does http://sub-example.com return a 404 status code?

**Comment by samboman** [comment]
No, that’s maybe the “problem”...
http://sub-example.com returns the same page as example.com, so it’s valid. 
Better to handle this in URL Rewrite then?.. Or can I force it?

//Sam

**Comment by marisks** [comment]
Yes, it is better to handle such scenario with URL Rewrite.

404 handler redirects only requests which return 404 status.

**Comment by samboman** [comment]
I see, thanks for quick support!

//Sam
