### ISSUE TITLE
AppPool Error when using BVN404 redirect tool.

### ISSUE THREAD

**Issue by Ram-K-Kumar** [Geta/404handler#113]
A process serving application pool "AppPoolName" suffered a fatal communication error with the Windows Process Activation Service.
When i turned off  <bvn404Handler handlerMode="Off", we did not have any issues.
We are using Latest Version of Episerver Update 217 (June 4th 2018)
.net Frame work 4.7.1

**Comment by marisks** [comment]
How many redirects do you have defined?

**Comment by Ram-K-Kumar** [comment]
I've 200 redirects and also i'm using the Version 11.1.12

**Comment by marisks** [comment]
Could you give more information by logging the actual error?
You can follow these suggestions: https://forums.iis.net/t/1193644.aspx
