### ISSUE TITLE
Issue: Deleted short url still redirecting due to caching 

### ISSUE THREAD

**Issue by GauravBhatiaBain** [Geta/404handler#114]
I removed the short url from the gadget and browser still redirecting the user based on the deleted short url. It may be happening due to the browser cache. Do we have any solution to handle this issue?

Thanks in advance!

**Comment by marisks** [comment]
There is no solution to this. A permanent redirect is "permanent" - the browser will cache it forever until you delete the cache.

**Comment by GauravBhatiaBain** [comment]
@marisks  thanks
