### ISSUE TITLE
NOT WORKING: You can turn off the redirects by setting handlerMode to Off

### ISSUE THREAD

**Issue by GauravBhatiaBain** [Geta/404handler#115]
I turned off the handlerMode to Off but my redirects are still working.

**Comment by marisks** [comment]
Do those still work when you browse in incognito mode?

**Comment by GauravBhatiaBain** [comment]
@marisks Yes, it's redirecting even in incognito mode.

**Comment by GauravBhatiaBain** [comment]
version: 11.1.12
Yes, I cleared the cache and still redirects.
yes, I have rewrite rules but that applied to specific URL.
![image](https://user-images.githubusercontent.com/11024330/41274854-8dd1274e-6e3c-11e8-880f-1edfe91740c5.png)

**Comment by marisks** [comment]
This should be fixed in the latest versions for both Epi 10 and 11.
