### ISSUE TITLE
System.ArgumentOutOfRangeException error thrown by 404handler

### ISSUE THREAD

**Issue by jesperkristensen** [Geta/404handler#117]
We see a number of these errors in our logs:

```
BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization : Error on 404 handling.
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
at System.String.Substring(Int32 startIndex, Int32 length)
at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectCollection.UrlIsOldUrlsSubSegment(String url, String oldUrl)
at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectCollection.FindInternal(String url)
at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectCollection.Find(Uri urlNotFound)
at BVNetwork.NotFound.Core.RequestHandler.HandleRequest(Uri referrer, Uri urlNotFound, CustomRedirect& foundRedirect)
at BVNetwork.NotFound.Core.RequestHandler.Handle(HttpContextBase context)
at BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization.OnEndRequest(Object sender, EventArgs eventArgs)
```

I tried to make a pull request, but I couldn't find out what the thought behind the code was, so I was not sure what the expected behavior should be. Here is a unit test which currently fails:

```
        [Fact]
        public void Find_should_not_throw_on_query_string_prefix()
        {
            var requestUrl = "/old/?param1=value1&param2=value2";
            var storedUrl = "/old/?param1=value1";
            var redirect = new CustomRedirect(storedUrl, DefaultNewUri.PathAndQuery);
            _sut.Add(redirect);

            var actual = _sut.Find(requestUrl.ToUri());

            //Assert.NotNull(actual);
        }
```

**Comment by jaytem** [comment]
Any resolution for this issue? We are seeing similar errors on the DXC environments.

**Comment by americares** [comment]
Ditto

**Comment by CasperCBroeren** [comment]
From my experience it happend when a custom redirect overshadows a handler.
**Custom redirect**
/nl/site?pageId=3  redirect to /products 

**Handlers**
`   public class PageIdHandler : INotFoundHandler
    {
        public string RewriteUrl(string url)
        {
            var uri = new Url(url.ToLower());

            if (uri.QueryCollection["pageid"] != null)
            { 
                return "/";
            }

            return null;
        } 
    }`

So the url _/nl/site?pageId=8_ was working (got redirected to /)
But then users tried _/nl/site?pageId=3&something=else_ and we expected to let them redirect to / as well but the error occured in the logs and the user saw a 404
Still the url _nl/site?pageId=3_ worked and got redirect to /

Btw to make things more complex our old urls could contain other parameters which had to be handled by an other handler. So if the old url  is _/nl/site?pageId=3&cat=12_ then we want them to go to /category/{catId}

To solve my problem I removed custom redirect

**Comment by marisks** [comment]
This should be fixed in the latest versions for both Epi 10 and 11.
