### ISSUE TITLE
Partial match on deleted-urls always gives NullReferenceException

### ISSUE THREAD

**Issue by johanandrel** [Geta/404handler#118]
We have problems with frequent NullReferenceExceptions on requests that get a partial hit in URLs that have a Deleted-state. I have reproduced this with a unit test and as far as I can se the code will always give a NullReferenceException if you have an item in the list that is i.e. "/deletedUrl" and you get a request with "/deletedUrl/andMore". 

I have attached two unit tests to verify that it works with an excact match and does not work with a partial match. If you put these tests in CustomRedirectCollectionTests.cs in the unit test project it can be reproduced.

       [Fact]
        public void Find_does_not_give_nullreferenceexception_with_exact_deleted_hit()
        {
            var storedUrl = "/contentassets";
            var requesttUrl = "/contentassets";
            var redirect = new CustomRedirect(storedUrl, (int)DataStoreHandler.State.Deleted, 1);
            _sut.Add(redirect);

            var actual = _sut.Find(requesttUrl.ToUri());

            Assert.NotNull(actual);
        }

        [Fact]
        public void Find_gives_nullreferenceexception_with_partial_deleted_hit()
        {
            var storedUrl = "/contentassets";
            var requesttUrl = "/contentassets/moreurl";
            var redirect = new CustomRedirect(storedUrl, (int)DataStoreHandler.State.Deleted, 1);
            _sut.Add(redirect);

            var actual = _sut.Find(requesttUrl.ToUri());

            Assert.NotNull(actual);
        }

**Comment by marisks** [comment]
This should be fixed in the latest versions for both Epi 10 and 11.
