### ISSUE TITLE
Weird behavior for some redirects

### ISSUE THREAD

**Issue by alpbso** [Geta/404handler#119]
Hello

We are using this 404handler v10.1.1 for our EPiServer v10.10.4 CMS and v10.8.0 Commerce solution and is experiencing some weird behavior with some of our redirects.
![image](https://user-images.githubusercontent.com/43142626/45628353-2d231480-ba94-11e8-8ba6-45586baeeec9.png)

The first redirect for /rygsaek-classic-boy is working correctly. However /rygsaek-classic-boy-1 redirects to the same URL as /rygsaek-classic-boy but with a /-1 at the end:
localhost:port/rygsaek-classic-boy-1 -> localhost:port/tickettoheaven-rygsaek-classic-boy-id-13724500000/-1/

Can you help us eliminate this unintentional behavior?

Thanks in advance.

**Comment by marisks** [comment]
Do you use the latest version of 404handler for Episerver 10?

**Comment by alpbso** [comment]
I've just upgraded to v10.3.11 which I found to be the latest version for Episerver 10 and the behavior still occurs.

**Comment by alpbso** [comment]
However all of these are working as intended:
![image](https://user-images.githubusercontent.com/43142626/45629995-08c93700-ba98-11e8-906e-fbf7bd07d90f.png)
