### ISSUE TITLE
Issue with Redirect links that don't match the old url exactly

### ISSUE THREAD

**Issue by RhinonMike** [Geta/404handler#120]
We are using 404handler v11.1.12 with our EPiServer v11.9.1 CMS DXC and we're having issues with redirect links that have a trailing slash and with links that have url variables.

Old Url | New URL
------------ | -------------
/unsubscribe.aspx | /unsubscribe
/assetmanagement | /corporate-cash-management-services

`https://www.domain.com/unsubscribe.aspx` works
`https://www.domain.com/unsubscribe.aspx?email=test@domain.com&src=email` doesn't work

`https://www.domain.com/assetmanagement` works
`https://www.domain.com/assetmanagement/` doesn't work
`https://www.domain.com/assetmanagement?id=test` doesn't work
`https://www.domain.com/assetmanagement/?id=test` doesn't work

All the above work on our PreProduction environment but not on our Production environment.  The interesting thing is they will occasionally work in our Production environment, but never more than a day.  

Do you have any ideas with what might be going on with the redirects?  We're thinking the CDN might be interfering.

**Comment by marisks** [comment]
We have tried to reproduce it with URLs you gave, and it seemed working.

If it randomly doesn't work, then it is likely related to heavy caching - Cloudflare in DXC could cause it.
