### ISSUE TITLE
Dashboard crashes on click at "Show Redirects"

### ISSUE THREAD

**Issue by nitinanand27** [Geta/404handler#123]
Hi we are using **Episerver CMS 11.6** and **BVNetwork.Epi404  v4.0.30319**

There are current **6000** redirects. 

The moment we click at "**Show redirects**", we get following console error and after a while , the redirects are shown in dashboard.  

`**DojoDashboardCompatibility.js:1** Uncaught TypeError: Cannot read property 'jQuery1538986477128' of null
    at Function.data (DojoDashboardCompatibility.js:1)
    at init.e (DojoDashboardCompatibility.js:1)
    at HTMLFormElement.<anonymous> (DojoDashboardCompatibility.js:1)
    at HTMLFormElement.handle (DojoDashboardCompatibility.js:1)
    at HTMLFormElement.<anonymous> (DojoDashboardCompatibility.js:1)
data @ DojoDashboardCompatibility.js:1
e @ DojoDashboardCompatibility.js:1
(anonymous) @ DojoDashboardCompatibility.js:1
handle @ DojoDashboardCompatibility.js:1
(anonymous) @ DojoDashboardCompatibility.js:1`

Is this a bug/defect? Any solutions to this?

**Comment by nitinanand27** [comment]
correction BVN Network version 11.1.11

**Comment by marisks** [comment]
From your description, it doesn't seem 404 handler issue as it loads redirects.

**Comment by nitinanand27** [comment]
true, but on live site (rests on azure) it doesn't show redirects and comes with an error message "Sorry, an error occured" 
screenshot attached
![image](https://user-images.githubusercontent.com/15047308/46800906-5fedbf00-cd59-11e8-824a-b4ddb518d8c6.png)

**Comment by nitinanand27** [comment]
**also, we here i'd like to mention the error i get from cloudfare** 

`Error 524 Ray ID: 4680f4586bff3ce3 • 2018-10-11 11:25:04 UTC
A timeout occurred
You
Browser
Working
Copenhagen
Cloudflare
Working
www.nameofmysite.com
Host
Error
What happened?
The origin web server timed out responding to this request.

What can I do?
If you're a visitor of this website:
Please try again in a few minutes.

If you're the owner of this website:
The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application. Additional troubleshooting information here.

Cloudflare Ray ID: 4680f4586bff3ce3 • Your IP: 11.11.1111.111 • Performance & security by Cloudflare`

**Comment by dotcentric-samb** [comment]
Hi
I am having a similar issue on my site, running in azure (DXC) using latest version of Episerver. When i click the suggestions tab i get the loading animation and after a few seconds the browser is unresponsive. This happens in chrome, firefox and Opera.

Has anyone got this module to work with DXC before? is it supposed to be compatible with dxc?

Sam

**Comment by marisks** [comment]
This is a known issue. I am in process of moving data access from DDS to SQL table. It should work faster after an upgrade.
The current status is that I have implemented SQL access but have to implement a migration from DDS to SQL.
I cannot give you an exact release date yet though.

**Comment by dotcentric-samb** [comment]
thanks for the quick response, marisks. i'll inform the website owner that this part of the bvn functionality isn't working, we'll plan to upgrade the package whenever a new version is out.

I also have an issue where the redirects i add only work when i check the wildcard checkbox, Is that also a known issue?

Sam

**Comment by marisks** [comment]
@dotcentric-samb No, I do not know anything about such issue. Could you please create a new issue and add examples of old/new urls and what you expect it should do.

**Comment by dotcentric-samb** [comment]
@marisks i can't get the issue with wildcards to work consistently, it only seems to be affecting one link so i'm going to leave it for now. i will let you know if the issue comes up again.

One other bug i have noticed is that when the widget is loading the list of redirects (for instance when i go to the custom redirects tab and check the show redirects box) it takes a while for the list to load (roughly 20 seconds).I assume this is related to the database issue you are looking to fix, however i also noticed that during this time it is not possible to access the site. Any requests to the site do not resolve until after the custom redirects widget has finished loading.

Is this related to the issue #123 or would you like me to create a new issue for it?


Sam

**Comment by marisks** [comment]
Yes, it looks like a performance issue of DDS. But it is strange that it is blocking all other requests. Is it happening on your computer or on the server?

**Comment by Sebbe** [comment]
I can confirm that it blocks all other requests while I add a new redirection at least

**Comment by marisks** [comment]
The latest version should perform much better now as it uses SQL table instead of DDS. Check for more info: http://marisks.net/2018/12/31/refactoring-404-handler-to-use-sql-store/
