### ISSUE TITLE
Dashboard gadget no longer available/visible

### ISSUE THREAD

**Issue by MEmanuelsson** [Geta/404handler#125]
Not sure when this happened but at some point in time, probably after some upgrade of Episerver, the 404Handler gadget went missing. We're currently running the following version of Episerver:
 Episerver.Cms.UI.Core: 11.7.0
 Episerver.Framework: 11.9.4
 Episerver.Cms.UI: 11.7.0

I've enabled logging as explained in the "Troubleshooting" section of the documentation but nothing is being logged in to the file. 

The bvn404handler section in web.config looks like this:
```
<bvn404Handler handlerMode="On" ignoredResourceExtensions="css,js,ico,swf,woff,eot,otf" logging="Off">
    <providers>
    </providers>
</bvn404Handler>

```
Is this something that any else has come across as a problem?
/Martin

**Comment by marisks** [comment]
Did you have this in the config?

```
<episerver.shell>
    <protectedModules>
        <add name="BVNetwork.404Handler" />
    </protectedModules>
</episerver.shell>
```

**Comment by MEmanuelsson** [comment]
Ahh, stupid! I should have read that part of the documentation more thoroughly and actually looked at that part of web.config as well. That part must have been lost in a merge conflict at some point in time. Thanks for your quick response!!
