### ISSUE TITLE
Sometimes redirects don't happen, or at least not immediately.

### ISSUE THREAD

**Issue by jdbosley** [Geta/404handler#126]
I've noticed that sometimes when I set up a redirect it works immediately, and sometimes it doesn't seem to work at all. But then maybe a few days later it begins to work. Do you know what may cause this? For example, the below redirect I set up roughly a week ago and it was not actually redirecting until I tried it today. There had not been a previous redirect in place, so it can't be a cached redirect issue.
![unnamed](https://user-images.githubusercontent.com/2483051/49605753-010e8580-f957-11e8-8618-0f6f350a6d35.png)

**Comment by marisks** [comment]
We just tried to reproduce the issue and couldn't. It seems that it is related to your setup. 

It could be related to Episerver caching or CDN. Also, note that it redirects only if the "Old url" is not found - when it returns 404 status code.

**Comment by jdbosley** [comment]
OK, thanks. I'll do some more digging.
