### ISSUE TITLE
Problem with redirect of image

### ISSUE THREAD

**Issue by scrog** [Geta/404handler#139]
If I add a redirect for a .svg file address everything works as expected.
If I add a redirect for a .png file address I ger a 404:error.

Is this a known issue?

Regards

**Comment by rustichowie** [comment]
I'm also experiencing this. 
Version: 11.1.12

**Comment by scrog** [comment]
Found the solution myself:
By default, requests to files with the following extensions will be ignored by the redirect module: jpg,gif,png,css,js,ico,swf,woff

If you want to specify this yourself, add ignoredResourceExtensions to the configuration:

<bvn404Handler handlerMode="On" 
               ignoredResourceExtensions="jpg,gif,png,css,js,ico,swf,woff,eot,otf">
</bvn404Handler>

[Source](https://github.com/Geta/404handler) section **Specifying ignored resources**
