### ISSUE TITLE
startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by AlexB-Adv** [Geta/404handler#140]
Hi,
we're investigating the reason our site has been freezing recently. One of the items in the logs around the time is the following:

```
EXCEPTION
System.ArgumentOutOfRangeException
Exception Properties
Show all
Event time    1/25/2019, 2:09:56 PM    
Message    startIndex cannot be larger than length of string.
 Parameter name: startIndex    
Exception type    System.ArgumentOutOfRangeException    
Failed method    BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectCollection.UrlIsOldUrlsSubSegment
```

We're running EPiServer 11 in DXC so I'm assuming that this [seemingly related post](https://github.com/Geta/404handler/issues/117) is no longer relevant.

Anyone have any ideas as to what could be causing this?
thanks in advance.
Alex

**Comment by marisks** [comment]
Is this still an issue? If it is, please test with the latest version: https://nuget.episerver.com/package/?id=Geta.404Handler and add tests that prove the issue.
