### ISSUE TITLE
404Handler Error 

### ISSUE THREAD

**Issue by IvAp76** [Geta/404handler#141]
Hi 
i have a integration, staging and production environment on Azure

BVN404 handler works fine at integration and staging but i get at error in production. 

Same configuration.  I get the following error: 

System.ArgumentException:"Must specify valid information for parsing in the string."
OS Thread Id:6272
  System.Enum+EnumResult.SetFailure(N/A, N/A, N/A, N/A)
  System.Enum.TryParseEnum(N/A, N/A, N/A, N/A)
  System.Enum.Parse(N/A, N/A, N/A)
  BVNetwork.NotFound.Core.Configuration.Configuration.get_Logging(N/A)
  BVNetwork.NotFound.Core.RequestHandler.HandleRequest(BVNetwork.NotFound.Core.RequestHandler, System.Uri, N/A, N/A)
  BVNetwork.NotFound.Core.RequestHandler.Handle(BVNetwork.NotFound.Core.RequestHandler, System.Web.HttpContextWrapper)
  BVNetwork.NotFound.Core.ErrorHandler.Handle(N/A, N/A)
  BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization.OnError(N/A, N/A, N/A)
  System.Web.HttpApplication.RaiseOnError(ASP.global_asax)
  System.Web.HttpApplication.RecordError(N/A, N/A)
  System.Web.HttpApplication+PipelineStepManager.ResumeSteps(System.Web.HttpApplication+PipelineStepManager, N/A)
  System.Web.HttpApplication.BeginProcessRequestNotification(N/A, N/A, N/A)
  System.Web.HttpRuntime.ProcessRequestNotificationPrivate(System.Web.HttpRuntime, System.Web.Hosting.IIS7WorkerRequest, System.Web.HttpContext)
  System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(N/A, System.IntPtr, N/A, N/A)
  System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(N/A, N/A, N/A, N/A)
  System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(N/A, N/A, N/A, N/A)
  System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(N/A, N/A, N/A, N/A)

Suggestions?

**Comment by marisks** [comment]
It seems that you have an invalid value for "logging" attribute in the Web.config. Valid values are "On" or "Off".

`<bvn404Handler handlerMode="On" fileNotFoundPage="/NotFound" logging="On">`
