### ISSUE TITLE
Not working after installing EPiServer.Marketing.Testing

### ISSUE THREAD

**Issue by scrog** [Geta/404handler#144]
After installing the nuget packet EPiServer.Marketing.Testing the redirects stoped working,
When going to an adress that should give a 404 I get an 500 error.

Nothing shows up in any logs,

If I change httpErrors in web.config to:

    <httpErrors errorMode="Detailed" />
   <asp scriptErrorSentToBrowser="true"/>

I get an error when surfing to a non existing URL:
{
"$id": "1",
"Message": "An error has occurred.",
"ExceptionMessage": "The object has not yet been initialized. Ensure that HttpConfiguration.EnsureInitialized() is called in the application's startup code after all other initialization code.",
"ExceptionType": "System.InvalidOperationException",
"StackTrace": "   at System.Web.Http.Routing.RouteCollectionRoute.get_SubRoutes()\r\n   at System.Web.Http.Routing.RouteCollectionRoute.GetRouteData(String virtualPathRoot, HttpRequestMessage request)\r\n   at System.Web.Http.WebHost.Routing.HttpWebRoute.GetRouteData(HttpContextBase httpContext)"
}

**Comment by scrog** [comment]
Hi,
No one who has had the same problem and have a solution?

Regards,
Jens

**Comment by marisks** [comment]
I have both a 404 handler and Episerver.Marketing.Testing and have no issues. Why do you think that this is a 404 handler issue?

**Comment by marisks** [comment]
Closing as no more info.
