### ISSUE TITLE
Language not set by NotFoundPage attribute

### ISSUE THREAD

**Issue by uggeh** [Geta/404handler#145]
* I use the attribute `[BVNetwork.NotFound.Core.NotFoundPage.NotFoundPage]`
* Request URL is "/sv/patrik-testing-invalid-url"
* I get pages in master language "en", but I want to get them in "sv"

![image](https://user-images.githubusercontent.com/1378698/53236982-e3b7a080-3695-11e9-8fd0-a18d241461ff.png)

Start page exists and is published in "sv":
![image](https://user-images.githubusercontent.com/1378698/53237449-05fdee00-3697-11e9-8f90-06af114f7bc0.png)

Am I doing something wrong or is this a bug?

**Comment by marisks** [comment]
I have fixed it. I have uploaded NuGet packages to the Episerver feed but have to wait for those to be approved. Versions: [11.2.2], [10.4.2]

**Comment by uggeh** [comment]
Great, looks nice!
