### ISSUE TITLE
Migrate redirects from DDS to SQL causes error

### ISSUE THREAD

**Issue by ErikJJonsson** [Geta/404handler#146]
We get the following error when we try to Migrate from DDS to SQL in version 11.2.3:

ERROR EPiServer.Global: Unhandled exception in ASP.NET
System.Data.SqlClient.SqlException (0x80131904): The parameterized query '(@id uniqueidentifier,@oldurl nvarchar(2000),@newurl nvarchar(20' expects the parameter '@newurl', which was not supplied.
   vid System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   vid System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   vid System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   vid System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   vid System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   vid System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   vid System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   vid System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   vid BVNetwork.NotFound.Core.Data.SqlRedirectRepository.<>c__DisplayClass19_0.<ExecuteNonQuery>b__0()
   vid EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.<>c__DisplayClass34_0.<Execute>b__0()
   vid EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.<>c__DisplayClass31_0`1.<Execute>b__0()
   vid EPiServer.Data.Providers.SqlTransientErrorsRetryPolicy.Execute[TResult](Func`1 method)
   vid BVNetwork.NotFound.Core.Data.SqlRedirectRepository.Create(CustomRedirect entity)
   vid BVNetwork.NotFound.Controllers.NotFoundRedirectController.MigrateDdsToSql()
   vid lambda_method(Closure , ControllerBase , Object[] )
   vid System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   vid System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   vid System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   vid System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   vid System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   vid System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   vid System.Web.Mvc.Controller.ExecuteCore()
   vid System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
   vid EPiServer.Shell.Web.Mvc.ModuleMvcHandler.ProcessController(IController controller)
   vid EPiServer.Shell.Web.Mvc.ModuleMvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   vid System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   vid System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   vid System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by ErikJJonsson** [comment]
I'm not sure if this is related or if it's another issue but de dashboard gadget shows: 
There are currently stored 0 custom redirects and 93981 custom redirect suggestions

In our EPi10 solution the same gadget shows:
There are currently stored 430 custom redirects and 93981 custom redirect suggestions

The database for EPi11 is a copy of the one for Epi10.

**Comment by ErikJJonsson** [comment]
I tried to export the redirects to XML-file from Epi10 and import them in Epi11.
That worked but migration still fails with the same error message.

**Comment by marisks** [comment]
The issue for this exception is that one "NewUrl" has NULL value. As a workaround remove all empty items and it will work.

**Comment by ErikJJonsson** [comment]
I don't see any empty items so I dont know how to remove them.
Any suggestions?

**Comment by breizh22** [comment]
I don't have any items with empty "NewUrl" and I still get the same error :
System.Data.SqlClient.SqlException (0x80131904): The parameterized query '(@id uniqueidentifier,@oldurl nvarchar(2000),@newurl nvarchar(20' expects the parameter '@newurl', which was not supplied.
   vid System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   vid System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   vid System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   vid System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   vid System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   vid System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   vid System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   vid System.Data.SqlClient.SqlCommand.ExecuteNonQuery()

**Comment by ErikJJonsson** [comment]
I tested to downgrade to version 11.0.0 and then all Ignored URL back which are missing with the latest version.
There seems to be some changes in how data is stored in the DDS between 11.0.0 and the latest version which cases these problems (redirects, ignored and migration).

**Comment by ggroot** [comment]
this query fixed it for me. Is it possible to add something like this prior to the migrate?

delete 
  FROM [episerverDB].[dbo].[tblBigTable] where storename = 'BVNetwork.FileNotFound.Redirects.CustomRedirect' and String01 is null

**Comment by matt656** [comment]
Sounds like many of you didn't follow the migration steps as instructed in the release notes:
If you are upgrading this package from a version previous to 11.2.0 (or 10.4.0 for CMS 10), you should run a migration of data. Open administration view on the gadget and under "Migrate redirects from DDS to SQL." click "Migrate." It will take some time depending on how many redirects you have. After the migration, the message will be displayed with information about how many redirects were moved to the SQL store. The message looks like - "Migrated 1000 redirects from DDS to SQL".

**Comment by nitinanand27** [comment]
Hi, we currently upgraded episerver CMS from 10 to 11 and missed the migration step. How to get the redirects back?

**Comment by nitinanand27** [comment]
we upgraded and found no redirects from "show redirects". We found that we missed the migrate step and once done, the redirects are back. @ErikJJonsson
