### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by Slippersen** [Geta/404handler#147]
A customer was adding custom redirects and managed to create duplicate entries: 

![image](https://user-images.githubusercontent.com/5341353/54906423-85bfe800-4ee3-11e9-9831-beb0c37d94bd.png)

When trying to remove one or the other, it fails: 

![image](https://user-images.githubusercontent.com/5341353/54906505-a6883d80-4ee3-11e9-9055-446dd2ee0840.png)

This issue also causes new custom redirects to fail. They can be added, but do not redirect from old URL to new URL. 

Permanently deleting all entries have not been attempted.

**Comment by t-my** [comment]
Also Importing duplicate entries will result in a generic error message.

**Comment by marisks** [comment]
The upcoming latest version should fix the issue and just replace the existing redirect with the same `Old URL`.
