### ISSUE TITLE
Package preventing Indexing with Episerver.Search

### ISSUE THREAD

**Issue by Mantus667** [Geta/404handler#155]
We want to use the backoffice search for media items and blocks.
For this Episerver.Search has to be installed.

With this setup, we faced a problem where the calls to the IndexingService all are generating 404 responses.

I got the default message to pop up with adding this to the IndexingService section in the web.config: httpErrors errorMode="DetailedLocalOnly" existingResponse="Auto" 

But still, the actual endpoints are throwing 404: ERROR EPiServer.Search.Internal.RequestHandler: Update batch could not be sent to service uri 'http://localhost:56979/IndexingService/IndexingService.svc/update/?accesskey=local'

Is there a setting that prevents 404 handling for the service or do we have to implement our own custom handler that ignores all calls to the service?

**Comment by marisks** [comment]
The 404 handler catches all 404 exceptions and responses. If the indexing service throws not found exceptions, then the exceptions will be caught and handled by the 404 handler. But if there will be no redirects configured for a particular URL, then this will not be handled and passed to the next handler in the pipeline.
