### ISSUE TITLE
NullreferenceException after deleting a Redirect

### ISSUE THREAD

**Issue by lkbev** [Geta/404handler#156]
CMS administrator reports custom redirects manager has stopped working after they deleted a redirect. The error is as follows when I try to view the custom redirects manager on the dashboard of our production episerver website.

Custom Redirects Manager
An error has occured in the dynamic data store: System.NullReferenceException: Object reference not set to an instance of an object. at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.LoadCustomRedirects() at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.get_Current()

Our episerver version is 10.5.0
BVNetwork.EPi404.dll version is 10.1.1.0

Since our production instance is hosted by epi, I have no way to view database tables to investigate if maybe an errant url record is the cause of this.

Any suggestions?

Thank you,

**Comment by lkbev** [comment]
another note to this- I exported all redirects from production to an xml file then loaded this XML file into my local database to try to recreate this issue locally but after loading in the XML file exactly as it is from production, I don't see the nullReferenceException in my localhost version. But it has the same redirects now as prod which does have the issue.

One other thing is, I have heard this happened before then eventually it just "fixes" itself. But I suppose I'd rather know more about it if anybody has any idea as to what could cause this.

thanks

**Comment by marisks** [comment]
This is an issue in an older version that we do not support. Please update.
