### ISSUE TITLE
Documentation for importing redirects from xml file

### ISSUE THREAD

**Issue by JasonRodman** [Geta/404handler#169]
I cant seem to find any mention of the format of the xml file used to upload redirects in batch. Can this be added to the documentation, and point me in the right direction?

**Comment by marisks** [comment]
That's strange that this article has not been added to the docs: https://getadigital.com/blog/import-redirects-for-404-handler/
Will add it later.

**Comment by marisks** [comment]
Added docs: https://github.com/Geta/404handler#import
