### ISSUE TITLE
Mismatch between SQL parameter size and SQL table column

### ISSUE THREAD

**Issue by apeneve** [Geta/404handler#170]
The create table script creates OldUrl in dbo.BVN.NotFoundRequests like this:
```
[OldUrl] [nvarchar](2000) NOT NULL,
```
DataAccessBaseEx.LogRequestsToDb creates oldUrl parameter like this:
```
var oldUrlParam = CreateParameter("oldurl", DbType.String, 4000);
oldUrlParam.Value = oldUrl;
```

If the Url is indeed longer than 2000 chars, the insert fails with a System.Data.SqlClient.SqlException "String or binary data would be truncated."

This mismatch in parameter/column size is valid for several other fields. The above is just one of them.

The parameters should be set to 2000 in size, or the table column(s) should be expanded.

**Comment by marisks** [comment]
Fixed
