### ISSUE TITLE
Wildcards not working as expected

### ISSUE THREAD

**Issue by JasonRodman** [Geta/404handler#173]
I am attempting to use your wildcards, but they do not work at all like I would expect and there is no documentation. I am attempting to redirect a single page and all of its sub pages to the root of the site, but for some reason its always appending the sub pages to the root of the site after the redirect. For example:

Redirect "/dakota" works just fine when going directly to that page. 
Redirect "/dakota/*" always appends the wildcard match part to the end of the target url.

This is not how I expected the wildcard checkbox to work. What am I missing?

**Comment by JasonRodman** [comment]
Now I have an issue after adding and removing these redirects several times, I cant get any of them to work. I simply want to redirect "/dakota" to "/" and it does not work at all. Its the only redirect in there. I have restarted the app and cleared the cloudflare cache and no luck. Not sure what I am doing wrong.

**Comment by JasonRodman** [comment]
How is this not working?
![image](https://user-images.githubusercontent.com/2798712/71689188-6659c380-2d6f-11ea-86bc-7ab3d03f1a03.png)

It still returns a 404 error. Even turned off caching in chrome dev tools and cleared cloudflare cache.
![image](https://user-images.githubusercontent.com/2798712/71689255-8ee1bd80-2d6f-11ea-9436-830a12fbe4ca.png)
![image](https://user-images.githubusercontent.com/2798712/71689305-b8024e00-2d6f-11ea-99f7-61525946c30b.png)

**Comment by LukaDevic** [comment]
@JasonRodman 
1) Regarding wildcard usage, this is a definition for using wildcards and will be shortly added to the documentation:           
        "If you want to redirect many addresses below a specific one to one new URL, set this to true. If we get a wild card match on       
         this URL, the new URL will be used in its raw format and the old URL will not be appended to the new one."
    If your subpages get appended to root URL after checking the wildcard box the issue may be that your subpages still exist and they are not set to expire or you are using an old version of Episerver or old package version, pls upgrade package to the latest version and upgrade Episerver version and see if the issue reoccurs.

2) Regarding "/dakota" redirection stopped working issues, I tried to recreate the issue but couldn't get it to occur, as above try upgrade package to the latest version and upgrade Episerver version and see if the issue reoccurs.

**Comment by marisks** [comment]
Added documentation: https://github.com/Geta/404handler#wildcards
