### ISSUE TITLE
Preserving parameters in url

### ISSUE THREAD

**Issue by baier** [Geta/404handler#184]
Hi, I'm trying to create a redirect that preserves url parameters, e.g.

_site.com/some-page?id=123_ => _anothersite.com/new-and-improved?id=123_

without manually plotting _?id=123_

Is this possible to do with the redirects module? If yes - how? Feel like I've tried everything with no progress.

**Comment by daniel-isaacs** [comment]
If you're just looking for all parameters to be passed through, that should happen automatically in my experience.

Ex: 
Old url: /gobackhome
New url: /
Wildcard: false

Result:
https://www.website.com/gobackhome?param=Value
will redirect to
https://www.website.com/?param=Value


Note:
1) it currently adds that extra slash before the querystring; there's a PR to fix that here: https://github.com/Geta/404handler/pull/185
2) if you use the wildcard option, it looks like the querystring gets stripped out

**Comment by LukaDevic** [comment]
@baier, regarding your question daniel-isaacs answered everything correctly, passing of all parameters happens automatically, parameters won't be preserved if you check wildcard checkbox.
