### ISSUE TITLE
Before (where the `<Buffer>` disappears because it is interpreted as an HTML tag:

### ISSUE THREAD

**Issue by abohosam1772** [Geta/404handler#194]
Before (where the `<Buffer>` disappears because it is interpreted as an HTML tag:
![image](https://user-images.githubusercontent.com/718899/92320924-2e7bdd80-efda-11ea-869f-0ec3dae6797c.png)

After:
![image](https://user-images.githubusercontent.com/718899/92320894-0a200100-efda-11ea-999f-9f216c0b57df.png)

_Originally posted by @Trott in https://github.com/nodejs/node/pull/35075#issuecomment-687718272_

**Comment by marisks** [comment]
How is this related to 404 handler?

**Comment by Trott** [comment]
> How is this related to 404 handler?

It's not and this should be closed, and probably a good idea to block/report abohosam1772 as a review of their contribution history shows only disruptive non-contributions like https://github.com/google/material-design-icons/issues/1075, https://github.com/ampproject/amphtml/issues/30097, and https://github.com/ampproject/amphtml/issues/28869.
