### ISSUE TITLE
Custom Redirects Manager in EpiServer not working

### ISSUE THREAD

**Issue by SG-2020** [Geta/404handler#197]
Hi,

Within our Episerver CMS, we have the third party plug-in 'Custom Redirects Manager' installed. We use this plug-in for all our redirects and we have never experienced any issues. Earlier this week, we added a redirect as per normal but it is not redirecting (see image attached). I followed up with Episerver support and they informed me that they are unable to provide support as this is a third party tool and to contact someone at Geta. 

As you can see in the image attached, the link is not redirecting where it should be. 
https://www.docscorp.com/footer/human-rights-policy/
https://www.docscorp.com/systems-outage/

Can you please provide further insight to this error and how this can be resolved? 
![Screen Shot 2020-10-22 at 1 14 03 pm](https://user-images.githubusercontent.com/73265499/96816755-96429680-1469-11eb-9fe3-5d2ece952664.png)

**Comment by evest** [comment]
It seems the https://www.docscorp.com/footer/human-rights-policy/ url is a working url, that has actual content.

Only not-found content (that generates a 404 error) will be redirected.

**Comment by SG-2020** [comment]
@evest we use this plug-in to place all our redirects, regardless if they have actual content or not. Are you aware of any changes made to this plug-in that may have impacted this?

**Comment by marisks** [comment]
@SG-2020 as Steve mentioned it redirects only if the "Old" URL returns 404. It is how it worked for many years, nothing has changed - that's the name of the project - 404 handler.
If you want to redirect existing URLs, you should use the [IIS URL rewrite module](https://www.iis.net/downloads/microsoft/url-rewrite).

**Comment by SG-2020** [comment]
Thank you all for your help. This has been resolved. Turns out we cannot redirect two live links.
