### ISSUE TITLE
Cloudflare 524 timeout when saving suggestions

### ISSUE THREAD

**Issue by tanujatbrightfind** [Geta/404handler#204]
When I try to add a NEW URL for suggested results. I am seeing a below 524 error. Custom redirects work correctly.

**Step 1: Try to setup a NEW URL for a Suggested OLD URL.** 

![image](https://user-images.githubusercontent.com/59699643/100264844-616ca800-2f1d-11eb-9cc4-fc232eaec3ca.png)

**Step 2: When I hit ADD button, I get below error:**

![image](https://user-images.githubusercontent.com/59699643/100259183-ece23b00-2f15-11eb-9bc8-84910a8f4853.png)

**Browser console shows error for "savesuggestions"**

**Comment by marisks** [comment]
Tried with the latest version of the 404 handler and no issues.
What Episerver version and 404 handler version do you have?

**Comment by tanujatbrightfind** [comment]
@marisks 
EPi Version: "11.12.0"
BVN.404Handler : "11.2.3"

**Comment by marisks** [comment]
You are using quite an old version of the package. Please update to the more recent version.
Here is the changelog: https://github.com/Geta/404handler/blob/master/CHANGELOG.md
