### ISSUE TITLE
500 error on trying to add new redirect

### ISSUE THREAD

**Issue by ranjit0829** [Geta/404handler#207]
Hello Geta Team,

We have recently  upgraded EPiServer CMS to v11.20.x and also we upgraded 404Handler to it's latest available. But after install we were able to see any data the data that "Custom Redirect Manager" from previous version. 

Secondly when we tried saving new record, old and new url it failed with 500 error. Please see the screen shots attached.

We followed the configuration steps provided but error persists. 

Please advise.

![Full-screen-1](https://user-images.githubusercontent.com/2822196/101753248-696d4000-3af8-11eb-8066-28fd35b3ebe4.JPG) - updated
![StackTrace-2](https://user-images.githubusercontent.com/2822196/101674780-f1166880-3a7e-11eb-806b-260e021b8cea.JPG)

Thank you in advance!

Regards,
Ranjit

**Comment by ranjit0829** [comment]
Hello Geta team, 

404handler source code has been forked and cloned to apply fix for the issue in Urls "Add" button format exception. 
PR raised for the branch "bug/fix-format-exception-url-add" to merge with master "https://github.com/ranjit0829/404handler/pull/1".

Please review and approve.

Thanks,
Ranjit

**Comment by marisks** [comment]
Please create a pull request for it.

**Comment by ranjit0829** [comment]
Hello marisks,

I have already created one: https://github.com/ranjit0829/404handler/pull/1/files

Thanks,
Ranjit

**Comment by marisks** [comment]
That is not a pull request to the library. It is a pull request to your fork.
Here are the docs, how to create a pull request from a fork: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ranjit0829** [comment]
Thank you for guiding link. 
Please check again for my PR. 

Cheers!

**Comment by marisks** [comment]
We will publish the fix tomorrow.

**Comment by ranjit0829** [comment]
Sounds great! :)

**Comment by ranjit0829** [comment]
Hello @marisks,

I hope you are well. 

Since you mentioned about publishing this change, we are looking forward get the latest version of Geta.404Handler on: https://nuget.episerver.com/package/?id=Geta.404Handler. 

We have setup continuous build and currently we are on hold to push our releases to our servers due to Geta.404Handler package. 

I request you to publish this change. If otherwise, if let us know the waiting period. 

Thanks,
Ranjit
