### ISSUE TITLE
Redirect without wildcard still including wildcard links

### ISSUE THREAD

**Issue by boat-priyanka-agrawal** [Geta/404handler#215]
Hello,
We are using 404handler v11.3.0 with our EPiServer v11.20.5 CMS and we're having issues with some redirect links.

So, I have added this redirect in the gadget (wildcard checkbox is unchecked)-

/insights/a  -> /insights/b/

which works fine.
But for 404 pages with url    --  /insights/a/d, I am getting redirected to /insights/b/d
Since the link is not set as wildcard, the redirect should only apply to specified url. We expect /insights/a/d to not get redirected.

How do I make sure that only exact url get redirected, and not sub pages?

**Comment by marisks** [comment]
If `/insights/a/d` returns 404 status code, then it will be redirected to `/insights/b/d`. If it does not return 404, then it will display the page.

Wildcard has a different meaning: https://github.com/Geta/404handler#wildcards

**Comment by boat-priyanka-agrawal** [comment]
Thanks Maris for the prompt response. Is then there any other way through the redirect manager, that I can still keep a 404 /insights/a/d  url as it is?

**Comment by marisks** [comment]
Only if you implement your own custom handler that would ignore this particular URL: https://github.com/Geta/404handler#custom-handlers

But why do you care on what URL it displays 404?

**Comment by boat-priyanka-agrawal** [comment]
Thanks Maris, we will look into the custom handler if we need to implement any custom logic. But for now, getting this information is helpful!
