### ISSUE TITLE
relative url redirect not working for different languages

### ISSUE THREAD

**Issue by boat-priyanka-agrawal** [Geta/404handler#216]
Hello,
We are using 404handler v11.3.0 with our EPiServer v11.20.5 CMS and we're having issues with relative url for different languages.

For this url, we are getting a 404-  hostname/it/our-team/toshihiko-hiura/

We have this redirect added -
![image](https://user-images.githubusercontent.com/70316089/116542912-d861fe80-a90a-11eb-940c-d0215d7ef16a.png)

But, the relative url is not accounting for different languages. Ideally according to the above rule , this url hostname/it/our-team/toshihiko-hiura/ should redirect us to hostname/our-team/

How can we achieve this?

**Comment by marisks** [comment]
Redirect is relative to the host. You should add redirects for each language. There is no other way.
