### ISSUE TITLE
Redirects rules not working (URL is not redirecting)

### ISSUE THREAD

**Issue by Aparna-C** [Geta/404handler#222]
We are using version 1.0.0.

We are experiencing issues where URL redirects not working when we add new URL. 

We can see all redirect rules in EPiServer Dashboard gadget and also in the database table. Also we are getting successful message after adding redirect rule. but URL is not redirecting.

Thanks in advance for your help.

**Comment by Aparna-C** [comment]
Hello Marisks,

Thanks for your reply.

I have updated the version and seems that EPiServer site is redirecting. (Ex- Old URL - https://www.knowhae.com/xsxcs New URL - https://www.knowhae.com/)
But we are trying to redirect WordPress site. (Ex - Old URL - https://www.de.huntersyndrome.info/public/home/hshfshfs New URL - https://www.leben-mit-hunter.de/). New URL is the EPiServer site. So we are trying to redirect WordPress site to EPiServer site. This redirection is not working.

Note - The WordPress site is going to decommission hence we need to implement this redirection.

Regards,
Aparna

**Comment by marisks** [comment]
I your case WordPress should handle redirects, not the Episerver site.

**Comment by evest** [comment]
You need a way for the Episerver site to get the decommissioned URLs, which means the old domains could be pointed to the new Episerver site. Then you'll get 404 errors that you can redirect.

**Comment by Aparna-C** [comment]
Hello,

Thanks Evest. 
We have one more scenario where we want redirection.  We have link reference to PDF and that PDF has expired. When we click on the link it is giving 404. We want to redirect this PDF to another PDF. Is this possible through this NuGet?

Regards,
Aparna

**Comment by Aparna-C** [comment]
Hello evest,

I have followed the below steps - 

1) I have expired the renamed PDF. So now it is giving me the 404 error message. (https://com-corp-prep2.cms.takeda.com/Recycle-Bin/20130424-1ba13launchpressreleasefinal1.pdf)

2) Later I have added entry in gadget. (URL https://com-corp-prep2.cms.takeda.com/Recycle-Bin/20130424-1ba13launchpressreleasefinal1.pdf and new URL https://com-corp-prep2.cms.takeda.com/4ab560/siteassets/system/newsroom/shire-press-releases/2013/august/notification-of-major-interests-in-shares/20130805-1transactioninownshares.pdf successfully saved.)

But still it is not redirecting. (Page URL - https://com-corp-prep2.cms.takeda.com/newsroom/shire-news-releases/2013/brave-awards-now-accepting-nominations/)
<img width="671" alt="Screenshot" src="https://user-images.githubusercontent.com/89073923/140882969-2a6e2728-fbbc-46c7-862e-4d82b12a7d38.png">

Could you please help. 

Regards,
Aparna

**Comment by marisks** [comment]
And this is on the Episerver site? https://com-corp-prep2.cms.takeda.com/Recycle-Bin/20130424-1ba13launchpressreleasefinal1.pdf

**Comment by evest** [comment]
When I visit:
https://com-corp-prep2.cms.takeda.com/Recycle-Bin/20130424-1ba13launchpressreleasefinal1.pdf
I get a 301 Moved Permanently with Location:
https://com-corp-prep2.cms.takeda.com/4ab560/siteassets/system/newsroom/shire-press-releases/2013/august/notification-of-major-interests-in-shares/20130805-1transactioninownshares.pdf

So:
1. People with the old url will get the new one. This works as intended.
2. On the page "brave-awards-now-accepting-nominations", the link indeed goes to the old url, and gets redirected for me. to the new Press Release.
3. The url shown on the page points to the recycle bin, but that is probably because it was deleted or moved there. Episerver detects this, and changes all links, as long as the file still exists.

From what I can see, this is working now, or did I misunderstand.

**Comment by Aparna-C** [comment]
Hello Evest,

We have added below redirection. but still it is giving 404 error. 
![image](https://user-images.githubusercontent.com/89073923/142159436-67778902-9aab-49e7-89f4-5cf8f44dc432.png)

We have renamed this file (/en-gb/home/what-we-do/our-products/combined-advate-adynovi-pi-sept-21.pdf) too in system. 

![image](https://user-images.githubusercontent.com/89073923/142159607-c9bc95fc-326a-4eb5-b010-b3c8827de063.png)

Could you please help us because we are still facing this 404 issue.

Thanks in advance.

Regards,
Aparna Chaudhari

**Comment by marisks** [comment]
@Aparna-C Can you check if `pdf` is not added to "Ignored extensions" in the configuration? https://github.com/Geta/404handler#specifying-ignored-resources

**Comment by Aparna-C** [comment]
Hello Marisks,

No, there is no extension added for pdf.

<bvn404Handler handlerMode="On" logging="Off">
    <providers>
      
      <add name="BVN404CustomRedirect" type="Takeda.Presentation.Features.Core.UI.BVN404CustomRedirectsHandler.BVN404CustomRedirect,Takeda.Presentation.Features.Core.UI" />
    </providers>
  </bvn404Handler>

Regards,
Aparna

**Comment by marisks** [comment]
Could it be that PDFs are not handled by ASP.NET? Maybe result cached in Cloudflare or somewhere else? Then 404 handler will not be able to do anything if the request never hits ASP.NET.

**Comment by Aparna-C** [comment]
Hello Marisks,

We will check for cache in Cloudflare. but we are struggling to redirect PDF. We have lots of issues pending related to redirection. We have two instances where the gadget is not working properly. 
1) The PDF file url is not redirecting even if we have expired, renamed or deleted the PDF. (https://com-corp-prod2.cms.takeda.com/4a724b/siteassets/en-gb/home/what-we-do/our-products/combined-advate-adynovi-pi-sept-21.pdf)
2) 404 project url is also not redirecting. (Old - https://www.de.huntersyndrome.info/public/home/ and New - https://www.leben-mit-hunter.de/)

Regards,
Aparna

**Comment by marisks** [comment]
2. Is https://www.de.huntersyndrome.info/public/home/ an Episerver site?
Regarding the 1. you have to make sure that the request is handled by ASP.NET.

**Comment by Aparna-C** [comment]
Hello Mariska,

Yes that is the episerver site. 1. Could you please guide us how we can sure that the request is handled by ASP.NET?

Regards,
Aparna

**Comment by marisks** [comment]
1. I can't help you with checking out if it is handled by ASP.NET. 
2. Checked that URL and it doesn't seem like Episerver site or it is stopped. Without running site in that URL and without 404 handler there, it will not work.
