### ISSUE TITLE
There is already an object named '404Handler.Redirects' in the database.

### ISSUE THREAD

**Issue by gabedeko** [Geta/404handler#223]
~~Hello,~~

~~Is the latest version of the 404Handler incompatible with Episerver 11?~~

~~If so, would it be possible for to use an older version of the tool without issue?~~

Update:

It's a database issue it seems.

**Comment by marisks** [comment]
This libraries latest version is for the Episerver 11

**Comment by gabedeko** [comment]
Thanks for the swift response. For some reason it stopped working for me and I now get the default 404 - Not Found page.

Even after trying to uninstall and reinstall multiple times it's the same issue.

I may just need to troubleshoot.

**Comment by gabedeko** [comment]
I think I've figured out the issue. Apparently there is already an object named '404Handler.Redirects' in the database.

Has anyone run into this issue before? I suppose I should just remove the existing object?

**Comment by marisks** [comment]
This table contains all redirects. When you start the project the first time, the table is created, and only then. There might be an issue during initialization when this table was created but a stored procedure that returns the DB version was not created. If it is the case, then you can remove this table.

So check if there is a stored procedure: bvn_notfoundversion.

**Comment by gabedeko** [comment]
Thanks again for the suggestion @marisks 

I was able to fix the issue by deleting the table **404Handler.Redirects** in the database, removing the add-on completely, and then reinstalling.

Much appreciated.
