### ISSUE TITLE
Custom Redirects Manager Not Working

### ISSUE THREAD

**Issue by mm-harper** [Geta/404handler#224]
Hi, 

Our client's website is having issues with the Custom Redirects Manager gadget in Episerver. When we create vanity URls, the transformations are not taking effect. 

Is this a known bug? What can we do to fix this issue? 

Thanks,
Mary Martin

**Comment by marisks** [comment]
What do you want to achieve? Do you have an example?

**Comment by mm-harper** [comment]
We have social campaign UTMs that we would like to hide with a shorter and simpler URL. We also have old pages that need to be redirected to new, updated pages. However, when we enter the New and Old URLs into the Custom Redirects Manager and click "Add", the URL transformation does not work. We've also tried this in incognito to double check. 

For example, this link (https://na.doosanequipment.com/en/dealers/us-id-twin-falls) should redirect to (http://doosandealers.com/Twin-Falls). This redirect is not working as expected. 

Is there something that needs to be fixed with the Custom Redirects Manager gadget?

**Comment by marisks** [comment]
I see that the page exists here: https://na.doosanequipment.com/en/dealers/us-id-twin-falls
It should return 404 if you want a redirect. 
This package redirects only when there are 404 errors. If you want to add a redirect from existing pages, you should use URL Rewrite or some other tool.

**Comment by mm-harper** [comment]
We don't need a 404 for these links, just a redirect to another URL. I was routed to this forum by the CMS system's support team for this gadget (see attached screenshot). Is there another forum that I need to reach out to? 
![Screenshot 2022-01-26 111858](https://user-images.githubusercontent.com/98481930/151378441-b4d57bec-97e9-483a-8dff-75216c08abd3.png)

**Comment by marisks** [comment]
404 handler will not work in your case. For existing pages, you should use URL Rewrite or something else. Talk with your developers.
