### ISSUE TITLE
Assets panel redirect search bar not working

### ISSUE THREAD

**Issue by mariano-pitameglia** [Geta/404handler#226]
Hi,

we are having an issue where the search bar of the redirect in the Assets panel is not returning any value. 
![image](https://user-images.githubusercontent.com/95697328/172470895-45bf5ec8-db10-48fa-b283-f59dc73a2c95.png)

![image](https://user-images.githubusercontent.com/95697328/172471040-e77a6817-9da0-4118-9369-0558184e4d15.png)

I wanted to know if any body has some insight in this issue.

Thank you
Mariano

**Comment by marisks** [comment]
Hi! This is not the 404handler functionality. That's something else.
