### ISSUE TITLE
XSS possible when importing files

### ISSUE THREAD

**Issue by prochnowc** [Geta/404handler#23]
When uploading import files it is possible to inject javascript code.
Use some HTTP tool to upload a file to the import function and modify the file name in POST data to include XSS.

**Comment by marisks** [comment]
I do not think that this is a real issue. The upload functionality is available only for authenticated users with edit rights. Of course, there might be evil users, or someone might hack the user's account and access edit mode. But then (s)he could do more harm by modifying content and doing other stuff.
