### ISSUE TITLE
Duplicate entries in XML cause import to fail.

### ISSUE THREAD

**Issue by debpu06** [Geta/404handler#29]
Currently the Add function in BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectCollection adds the CustomRedirect to a Hashtable before adding it to the List of entries. For the current site that I am working on, I noticed that when editors try to import it fails because they have entries where the only difference is in the character case of the old URL, i.e. /mypath/index vs /MyPath/index. Manually editing the XML is difficult because it is generated with hundreds of entries, so tracking down any duplicates is difficult.  Can we add a contains key check for the hashtable before adding the entry?

Thanks

**Comment by fremler** [comment]
I ran into the same issue today. Tried to upload a xml-file with thousands of entries, so it's pretty hard to identify duplicate entries. And the only error message you get is "Error uploading file".

**Comment by marisks** [comment]
The issue was fixed in the upcoming release. It will update an existing redirect instead of adding the new one.
