### ISSUE TITLE
Support for EPiServer Multisite Would be a very nice feature

### ISSUE THREAD

**Issue by gr3p** [Geta/404handler#30]

**Comment by evest** [comment]
Could you please elaborate a bit on this? It works in a multisite environment, but all redirects are global. If you add redirects using fully qualified urls (including host), I believe it should pick it up on a site by site basis (haven't verified it yet).

**Comment by stgaup** [comment]
Hi, when the logger logs a url that did not exist, it strips off the server/domain name part (Authority). With multisites there are different host headers pointing to different sites. However, it is not easy to see which site was accessed when the aforementioned information has been stripped away.

**Comment by ErikHen** [comment]
+1 on this

**Comment by marisks** [comment]
Fixed in the latest version.
