### ISSUE TITLE
Possibility to let site handle 404 if there is no redirect

### ISSUE THREAD

**Issue by andreasclair** [Geta/404handler#31]
On our clients site 404:s are handled by custom routing for a specific department of the site, since there are several subdepartments that have their custom 404 pages due to specific reasons. 

Therefore i would like the error to "let go" if the redirect can't be handled by the redirect module (Custom404Handler.cs, line 152). I can achieve that by removing `context.Server.ClearError()` in the SetStatusCodeAndShow404 method. 

Could this perhaps be a setting or can I handle this in another way?

Br, 
Andreas

**Comment by evest** [comment]
See #26, which is part of 10.1.1 in the feed. Feel free to close this if this will work for you.
