### ISSUE TITLE
trailing slash after every redirect.

### ISSUE THREAD

**Issue by JoVoOsCl** [Geta/404handler#36]
I have an issue that i try to make a redirect to a PDF on a specific subsite that I have. 
OldURL: /something
Newurl: https://domain.mydomain.dk/thisismypdf.pdf

The redirecter then puts a trailing slash after the new url causing a 404. 

Is this possible to fix? :)

**Comment by marisks** [comment]
I am not able to reproduce the issue. Do you still have it?

**Comment by marisks** [comment]
I have added a test which verifies that no trailing slash added.

**Comment by adnanzameer** [comment]
hi, I am facing the same issue. Is using "iis redirect" redirect might be causing this?

**Comment by marisks** [comment]
It could be so or you have some really old version.

**Comment by adnanzameer** [comment]
> It could be so or you have some really old version.

i have latest Episerver version and Geta Redirect handler.
