### ISSUE TITLE
Cannot create several culture specific redirects

### ISSUE THREAD

**Issue by vitaliizhovtyi** [Geta/404handler#38]
After adding culture specific redirect and it English equivaluent module crashes. 

Steps to reproduce:
1. Open module in Episerver
1. Add rule "/digtalpaent" ->  "/"
2. Add rule "/digtalpænt" -> "/"
3. Restart website to clean module cache
4. Open module in Episerver
5. Try to search rule by "/digtalp" string
Expected result: 2 previously added rules in the redirects list.
Actual result: An error has occured in the dynamic data store: System.ArgumentException: Item has already been added. Key in dictionary: '/digtalpaent' Key being added: '/digtalpænt' at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add) at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.LoadCustomRedirects() at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.get_Current()

![404handler_issue](https://cloud.githubusercontent.com/assets/28925385/26405128/0ef91940-409d-11e7-9c04-ea19d8f20e5e.png)

Issue is caused by using InvariantCultureIgnoreCase in line:
 this._quickLookupTable = new Hashtable((IEqualityComparer) StringComparer.InvariantCultureIgnoreCase);
in file BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectCollection

**Comment by marisks** [comment]
The package with the fix is available now.
