### ISSUE TITLE
gadget not showing

### ISSUE THREAD

**Issue by peetah74** [Geta/404handler#43]
Can't seem to find the gadget and I don't see anything in the logs.  using episerver 10.5

**Comment by Konrad77** [comment]
Same here, doesn't show up in EPiServer 10.8.

**Comment by Konrad77** [comment]
I solved my issue by adding this line: 
<protectedModules>
    <add name="BVNetwork.404Handler" />
</protectedModules>

It was not added during Install-package.

**Comment by DanValea** [comment]
Hi @Konrad77 ,
Where did you add that section? I've tired adding it web.config -> under  <episerver.shell> but it doesn't seem to do any difference.

**Comment by peetah74** [comment]
I also put it there @DanValea no luck on my side.  I also tried using BVNNetwork.EPi404

**Comment by NeskireDK** [comment]
I'm having the same issue, I've got no idea about where to open the Redirect Manager
Running  Episerver 11.2 + BVN vers: 10.1.1 - Clean project default Allow MVC.

Can't find the Gadget in the side menu like the i can with the default gadgets. - I checked plugin settings, its installed.

**Comment by marisks** [comment]
I have updated readme with required configuration:
https://github.com/Geta/404handler#configuration

There is a Web.config transform which should add the required configuration, but sometimes NuGet does not:
https://github.com/Geta/404handler/blob/master/src/web.config.install.xdt

**Comment by jesusescandon** [comment]
The solution from @Konrad77 it worked for me, thanks.
