### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by evest** [Geta/404handler#44]
![](https://img.shields.io/badge/maintainers-wanted-red.svg) 
This project needs new maintainers to be continued. If you are interested in participating (or taking control) over this project , please respond to this issue and we will get in contact.

There are numerous open issues that needs to be taken care of, additionally, the gadget framework in Episerver is deprecated requiring a rewrite of the UI parts.

Though the loading times have been improved, large sets of redirects could still take time. Moving these out of DDS and into regular tables is probably a good idea.

**Comment by marisks** [comment]
@evest we at Geta would like to take over the project.

**Comment by valdisiljuconoks** [comment]
+1

**Comment by hypknot** [comment]
@evest we at "Visma" would be happy to maintain this

**Comment by evest** [comment]
Sorry for taking so long, but finally, a decision has been made.

Since Geta volunteered first, the module will be handed off to them. We will change the license to MIT before doing so. As Geta also has an excellent track record for involving others and contribute to the open source community around Episerver, I believe they will happily accept PRs from everyone that wants to participate.

@marisks: I will contact you off-line to discuss the details if you're still up for it.

I'm very happy that we now have a plan for moving forward and to see a popular module continue to work also for newer versions of Episerver products.

**Comment by marisks** [comment]
@evest I am still up for it :)

**Comment by Dominhquan401** [comment]
#44
