### ISSUE TITLE
Permanent error state util web app restart

### ISSUE THREAD

**Issue by jakobtanentsapf** [Geta/404handler#48]
When the property (public static string CustomRedirectHandlerException { get; set; }) is set, sets the handler in a permanent error state forcing a web application restart.

CustomRedirectHandlerException is static and will retain it's value for all instances of the CustomRedirectHandler class. CustomRedirectHandlerException is never reset to a non error state.

**Comment by kennygutierrez** [comment]
Quick question, does this just cause a problem for the admin gadget or do redirects not work while this is in the error state?

**Comment by jakobtanentsapf** [comment]
It's just the gadget for the bug I reported on. But since the redirect data couldn't be loaded from the DDS and I couldn't remove the faulty values via the gandget, I had to remove the values from the database manually. The gadget still didn't work and the app had to be restarted to clear the static variable in memory.

**Comment by marisks** [comment]
@jakobtanentsapf what kind of faulty values did you have in the database? I am thinking that maybe loading of values should be fixed so that it will not break loading.

**Comment by jakobtanentsapf** [comment]
@marisks I'm unsure about the faulty values in the db, since this was reported a while back. But some cms-editor managed to enter one or more urls in the gadget that made it crash. The site is running as a web app in Azure with a restart time of about 10-20 min. Not something I wan't to do, so I modified the db directly and tried to reload the gadget, but I still got the error message even if the data was ok. All this because of the static exception property.

**Comment by marisks** [comment]
This should be fixed by #42
