### ISSUE TITLE
Add groupname to the Gadget Authorize attribute

### ISSUE THREAD

**Issue by defsteph** [Geta/404handler#49]
I know it would be a breaking change, but adding a groupname to the Authorize attribute on the Gadget controller, would enable access management for the Custom Redirects Manager.

One way to sort-of circumvent the breaking change's effect, could be to also add a config transform after install, that could add the group as a virtual role, including the de-facto standard CmsAdmins group.

**Comment by lanorkin** [comment]
Hi @defsteph @marisks 

I was able to achieve that using standard episerver feature as described here https://world.episerver.com/documentation/developer-guides/CMS/user-interface/views/Configuring-the-dashboard/

Added the following to web.config:

```
  <episerver.shell>
    <viewManager>
      <securedComponents>
        <add definitionName="BVNetwork.NotFound.Controllers.NotFoundRedirectController" allowedRoles="Administrators" />
      </securedComponents>
    </viewManager>
  </episerver.shell>
```

This is really flexible and standard, so I think this issue can be closed.

**Comment by marisks** [comment]
Documentation updated!
