### ISSUE TITLE
How to activate Gadget?

### ISSUE THREAD

**Issue by NeskireDK** [Geta/404handler#51]
I've installed this 404handler on two projects and am unable to get the gadget panel to show. I expected to find it possible to "add gadget" via the 2 sidemenues while editing a page, This however doesn't seem to be the case. My two projects are as follows:

Project 1, running Episerver version 8.1 
- Running BNB.404Handler vers. 3.1.2
Im running this version as itt's confirmed to work with CMS 8.1, ive tried every version up to 8.1, Followed readme tell me to manually clean up Web.config. 

Clean MVC alloy solution version 10.10.
- Running BNB.404Handler vers. 10.1.1

Ive played around and added the following lines in varies combination. 
```
<section name="bvn404Handler" type="BVNetwork.FileNotFound.Configuration.Bvn404HandlerConfiguration, BVNetwork.EPi404" />
....
<add name="BVNetwork.EPi404" type="BVNetwork.FileNotFound.Handler.CustomFileNotFoundHandler, BVNetwork.EPi404" />
....
<add assembly="BVNetwork.FileNotFound.RedirectGadget" />
....
<location path="modules/BVNetwork.FileNotFound.RedirectGadget">

```
The following issue didn't seem to help out either, unless im just blind as to how i should pull up the URL redirect manager.  https://github.com/Geta/404handler/issues/43

Thanks for your time, and excuse  me apparent stupidity.

**Comment by Sebbe** [comment]
Hi

The 404handler is a dashboard widget, so you need to go to the dashboardview and add the gadget there

https://i.imgur.com/kL1YYSY.png

**Comment by NeskireDK** [comment]
I'm amazed i hadn't thought of that. I love you.
In my defense, i've worked with episerver for 3 months and done about 1/3 of the courses. Mainy programmed for it.
