### ISSUE TITLE
Custom Redirect Manager not shown under Add Gadgets

### ISSUE THREAD

**Issue by BrianFrederiksen** [Geta/404handler#63]
Hi

I have encountered a problem, the Custom Redirect Manger is not showing under the "Add Gadgets" in the EPIServer CMS.

Im currently on version EPIServer.CMS.Core: 10.10.3

When following the installation guide, 

I installed version 10.2.0 BVN.404Handler

I have added the following in the web.config:

<episerver.shell>
    <protectedModules rootPath="~/dashboard/">
          ....
         <add name="BVNetwork.404Handler" />
    </protectedModules>
</episerver.shell>

<configuration>
   ....
   ....
     <bvn404Handler handlerMode="On">
    <providers>
      
    </providers>
  </bvn404Handler>
</configuration

I have also added the logging as described, but I get nothing in the log.

Do you have any idea, if I am doing anything wrong ?

**Comment by sh7dow** [comment]
Hi
The 404handler is a dashboard widget, so you need to go to the dashboardview and add the gadget there. Check this image:
https://i.imgur.com/kL1YYSY.png
Hope this help
