### ISSUE TITLE
Adding package Microsoft.CodeDom.Providers.DotNetCompilerPlatform

### ISSUE THREAD

**Issue by oyvindwh** [Geta/404handler#66]
In commit 93c56cb8caeceaaf8a8d43e1d7606219da11e8d4 you added the package Microsoft.CodeDom.Providers.DotNetCompilerPlatform and Microsoft.Net.Compilers. During a recent update of an old webforms project I got problem due to the missing roslyn\csc.exe needed file. I cloned the newest source and removed these two packages.  Then created a local nuget package and installed the 404Handler with success. 

To keep the source as simple as possible since there are many projects that use this module, what was the reason for adding these packages? Are they needed in some way?

**Comment by marisks** [comment]
These packages allow building project with latest compilers.
It sounds that packages were not restored/installed properly in your project. Maybe try forcing reinstalling those.

**Comment by oyvindwh** [comment]
Both packages was restored successfully but no roslyn is copied. Customers that use this module is sometimes placed on a shared server. According to this article (http://www.itorian.com/2015/09/roslyn-cscexe-and-vbcexe-deployment-on.html) roslyn will not work in shared environments. 

_Roslyn compilation will only work with Full Trust so on some shared hosting you might face challenges. I would suggest ask your hosting provider if they support Full Trust._

Have you done a deployment to a shared environment with the new packages?

I can not uninstall the Microsoft.CodeDom.Providers.DotNetCompilerPlatform since the 404 handler is depending on it (of course).

**Comment by marisks** [comment]
I have removed this dependency, will publish the package soon.

**Comment by marisks** [comment]
The package is published now.
