### ISSUE TITLE
404 page hanging for long time

### ISSUE THREAD

**Issue by ostensene** [Geta/404handler#69]
I just experienced the same bug as https://world.episerver.com/support/Bug-list/bug/CMS-1119. This bug is marked as "won't fix"

The should be a comment on the readme file telling you turn off globalErrorHandling in episerver when using custom error page.

**Comment by sandeepsahoogirik** [comment]
Hi 
Just to confirm in order to resolve the issue you need specifically turn global error handling off

<applicationSettings globalErrorHandling="Off"

Kind Regards
Sandeep
