### ISSUE TITLE
Fallback to english if translation is missing

### ISSUE THREAD

**Issue by madebykrol** [Geta/404handler#78]
![image](https://user-images.githubusercontent.com/1517565/36484820-be4e6202-171a-11e8-8059-8be98a19a717.png)

The gadget does not seem to fallback to English if you are working with the gadget with Swedish as personal language. 

Have I missed something? It works great if the language is set to English specifically. But it is pretty hard for a editor on the site to work with the gadget if the editor language is Swedish. Or maybe other languages.

Version: 10.3.0

**Comment by cromberg** [comment]
Also, if other language than English is used as Personal Language the gadget will not show up in the list of available gadgets. I spent a lot of time trouble shooting why I could not see the gadget in our test envrionment when it worked in dev. Turned out language was set to Swedish in test.

**Comment by viktor-knowit** [comment]
**+1**

![image](https://user-images.githubusercontent.com/31000362/58415127-ca9c0280-807d-11e9-998b-dad143b958b4.png)
_Image describing the problem._

**Comment by marisks** [comment]
The 404 handler uses Episerver localization service. If one wants a language fallback functionality, please ask Episerver to fix the issue. If one wants an additional language support, please add language XML and submit a PR.
