### ISSUE TITLE
ÆØÅ and ÄÖ in the "folder" part of the URL

### ISSUE THREAD

**Issue by MrKnUser** [Geta/404handler#8]
Hey,

I would like to request that it be made possible to add some of the scandinavian characters in the URL that needs to be redirected..

so:
OLD URL: www.domain.com/æøå/ 
NEW URL: www.domain.com/AOAA/

I noted a entry from EPiCode that says that the domain can include this type of character, but not the "rest"..

Can this be added? 

/Knudsen

**Comment by DorteaNoll** [comment]
Hi, this request would be very beneficial also for the new falck.dk website. We really needs this change to be able to handle redirects from  example falck.dk/førstehjælp, falck.dk/vejhjælp etc.
Thanks
/Dortea from Falck

**Comment by fatso83** [comment]
@MrKnUser: Can't you just create a `CustomHandler` that handles these specific cases? And then just feed it through a slugifier, such as [the one used by StackOverflow](http://stackoverflow.com/a/25486/200987)?

**Comment by MrKnUser** [comment]
First off, I'm not a developer, so it would not know where to start..  :)
Also, I'm sure it could be as "simple" as that, but being that we use this awesome add-on a lot on danish Episerver customer and some of them do use the wonderful ÆØÅ in the URL, it would be nice that this was part of the standard behavior...

**Comment by MrKnUser** [comment]
Hey any that read this.  

A solution to this was found..  Thank you SO MUCH Heino Simon Vig!!

The simple solution is to URL encode the "OLD URL" part of the setup..
So my old URL would be: http://cms9.epidk.dk/øst
The new URL would be: http://cms9.epidk.dk/en/alloy-track/

And the entry in the redirect manager looks like this:
OLD:
/%c3%b8st
NEW:
/en/alloy-track/

Not great, but 100% better then not working..  :)

Have a great one out there..

/KN

**Comment by marisks** [comment]
I think this should work now without a workaround. Now we are comparing URLs using ordinal comparison.
