### ISSUE TITLE
Can't get redirect to work with aspx-file extension

### ISSUE THREAD

**Issue by jonwid** [Geta/404handler#87]
Hi. Not sure if this is an issue or just me not configuring correctly. 
In our production environment I can't get the redirecting to work with the .aspx-extension, it works as expected without file extension.
I get this working in my local environment though, and comparing web.configs I can't see any differences.
errorMode is set to Custom and existingResponse to Replace.
Any ideas?

**Comment by bogdanstojanovic** [comment]
It is worth to check if you  have redirects inside web.config. If yes, ensure those rules accommodate with 404handler entries.

**Comment by marisks** [comment]
I have a site where I have redirects from .aspx to other page and it works fine. Maybe take a look at your other configuration.

Do you use the latest version?

**Comment by jonwid** [comment]
Ok. I upgraded from 11.0.0 to 11.1.5 and it started working. I haven't investigated further.

**Comment by marisks** [comment]
You should upgrade to the 11.1.6 once it will be available (I pushed the package to the nuget.episerver.com just now). This version includes several other bug fixes.
