### ISSUE TITLE
 existingResponse="Replace" Replaces 500 responses

### ISSUE THREAD

**Issue by russellshome** [Geta/404handler#9]
In web.config using existingResponse="Replace" will mean that in development 500 errors are not output to the browser making debugging more difficult than it needs to be.

Referring to http://stackoverflow.com/questions/717628/asp-net-mvc-404-error-handling/9026907

Application_EndRequest can be used to handle the 404 StatusCode.

What I do is check for a page with url /page-not-found and display the content of that page. This means there is an editable error page and 500 errors are handled properly.

<p><br /> protected void Application_EndRequest()<br /> {<br /> if (Context.Response.StatusCode == 404)<br /> {<br /> string baseUrl = HttpContext.Current.Request.Url.Authority;<br /> var contentLoader = ServiceLocator.Current.GetInstance&lt;IContentLoader&gt;();<br /> string pageNotFoundUrl = "/page-not-found";<br /> var content = UrlResolver.Current.Route((new UrlBuilder(pageNotFoundUrl)));<br /> Response.StatusCode = 404;<br /> Response.StatusDescription = "Page not found";<br /> if (content != null)<br /> {<br /> Response.Clear();<br /> pageNotFoundUrl = "http://" + baseUrl + pageNotFoundUrl;<br /> HttpWebRequest request = (HttpWebRequest)WebRequest.Create(pageNotFoundUrl);<br /> HttpWebResponse response = (HttpWebResponse)request.GetResponse();<br /> response.GetResponseStream().CopyTo(Response.OutputStream);<br /> }<br /> else<br /> {<br /> Response.Write(defaultOutput);<br /> }</p>

<p>}<br /> }</p>

<p>string defaultOutput = @"<br />&lt;!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Strict//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd""&gt;<br />&lt;html xmlns=""http://www.w3.org/1999/xhtml""&gt;<br />&lt;head&gt;<br />&lt;meta http-equiv=""Content-Type"" content=""text/html; charset=iso-8859-1""/&gt;<br />&lt;title&gt;404 - File or directory not found.&lt;/title&gt;<br />&lt;style type=""text/css""&gt;<br />&lt;!--<br />body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}<br />fieldset{padding:0 15px 10px 15px;} <br />h1{font-size:2.4em;margin:0;color:#FFF;}<br />h2{font-size:1.7em;margin:0;color:#CC0000;} <br />h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} <br />#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:""trebuchet MS"", Verdana, sans-serif;color:#FFF;<br />background-color:#555555;}<br />#content{margin:0 0 0 2%;position:relative;}<br />.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}<br />--&gt;<br />&lt;/style&gt;<br />&lt;/head&gt;<br />&lt;body&gt;<br />&lt;div id=""header""&gt;&lt;h1&gt;Server Error&lt;/h1&gt;&lt;/div&gt;<br />&lt;div id=""content""&gt;<br /> &lt;div class=""content-container""&gt;&lt;fieldset&gt;<br /> &lt;h2&gt;404 - File or directory not found.&lt;/h2&gt;<br /> &lt;h3&gt;The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.&lt;/h3&gt;<br /> &lt;/fieldset&gt;&lt;/div&gt;<br />&lt;/div&gt;<br />&lt;/body&gt;<br />&lt;/html&gt;<br />";</p>

**Comment by marisks** [comment]
You can disable response replace with PassThrough by default and use config transforms for test/staging/production environments to use Replace instead.
