### ISSUE TITLE
Issue with 'continuing' redirects

### ISSUE THREAD

**Issue by kaylabranch** [Geta/404handler#90]
![image](https://user-images.githubusercontent.com/25715079/37745880-601474c4-2d45-11e8-910c-5e2b8f21d114.png)

Seeing an issue for redirects like the above.

The pattern is that the old redirect matches the new one to a point, but the last segment of the new redirect is 'continued' from the old redirect - for example:
/resources/b -> /resources/blog
/product/health -> /product/health-insurance
/resources/articles/smal -> /resources/articles/small-business

A few examples:
**URL to hit**: /resources/blog/thisisablog
**Redirected to**: /resources/bloglogloglogloglogloglogloglogloglogloglogloglogloglogloglog/thisisablog

**URL to hit**: /product/health-insurance-article/what-hipaa-and-how-will-it-affect-your-small-business?q=article/what-hipaa-and-how-will-it-affect-your-small-business
**Redirected to**: /product/health-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-article/what-hipaa-and-how-will-it-affect-your-small-business?q=article/what-hipaa-and-how-will-it-affect-your-small-business

**URL to hit**: /resources/articles/small-business/understanding-financial-statements
**Redirected to**: /resources/articles/small-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-businessl-business/understanding-financial-statements

Any insight or fixes you can provide is much appreciated,
Kayla

**Comment by marisks** [comment]
I am unable to reproduce this. Which version of the package do you use?

**Comment by davidelias0** [comment]
We ran into this issue also.  We recently did a complete upgrade to 11.1.5 and we logged thousands of various BVN errors in our logs and eventually all 11 of our sites went down.  We backed down to 11.0.0 and have been stable.

**Comment by kaylabranch** [comment]
Hi @marisks - we are on 11.0.0

**Comment by marisks** [comment]
The package is not yet published. I am waiting for Episerver. Package version will be 11.1.7

**Comment by kaylabranch** [comment]
@marisks 
NICE - 11.1.7 fixed our issue here. Thank you
