### ISSUE TITLE
BVNetwork.EPi404 - Null Reference Exception

### ISSUE THREAD

**Issue by sziencik** [Geta/404handler#96]
Custom Redirects Manager

An error has occurred in the dynamic data store 'System.NullReferenceException': Object reference not set to an instance of an object. at BVNetwork.NotFound.Core.CustomRedirectHandler.LoadCustomRedirects(0 at BVNetwork.NotFound.Core.CustomRedirectHandler.get_Current()

Is there anyway to troubleshoot this issue.  We have been using module for about a year now with no issue.  This is a critical issue for our environment due to the fact that we cannot add any new items.  All existing redirects work but the UI fails to load.

We are using version 9.1.0.0

**Comment by cdo108** [comment]
We are having the same issue. I checked the database but nothing unusual there. Were you able to fix or troubleshoot the issue yet @sziencik ?

We are using version 10.10.4.0.

**Comment by marisks** [comment]
@americares which version of the package are you using?

**Comment by americares** [comment]
@marisks Thanks for your response. We're  version="4.1.1"

**Comment by marisks** [comment]
That is really old version. You should upgrade. Don't know if it supports Epi 10.x.

**Comment by marisks** [comment]
Closing as no response.

**Comment by SamDenHaerynck** [comment]
We are experiencing the same issue as mentioned above with one of the latest releases. 
EPiServer.CMS version 11.11.2 
BVN.404Handler version 11.0.0

As you mentioned we checked the database for "invalid values" (null, empty strings). 
Import/export is still working but this plugin is not long workable for the content editors without a UI.   (+2000 redirects)

**Comment by marisks** [comment]
@SamDenHaerynck It seems that you are using old version of the 404 handler. Try upgrading first.

**Comment by nehlwa** [comment]
We are also facing same issue with Custom Redirect Manager. 

EpiServer.CMS version 11.12.0.0
BVN.404Handler version 11.0.0

Frequently UI shows following error, and then after few days UI is up and running again.

_An error has occurred in dynamic data store: System.NullReferenceException: Object reference not set to an instance of an object. at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectsCollection.Add(CustomRedirect customRedirect)_

Is there solution found for this issue?

**Comment by LukaDevic** [comment]
@nehlwa, same as in @SamDenHaerynck comment, it seems that you are using the old version of the 404 handler. Pls try upgrading first and then see if the issue continues to occur.
